apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lscsde-config
configMapGenerator:
  - name: secret-distributor-config
    files:
      - values.yaml=secret-distributor-config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
- sources.yaml
- repository.yaml
- deployment-config.yaml