name: Create Release Branch from Main

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  package:
    uses: lsc-sde/lsc-sde/.github/workflows/flux-release.yaml@main
    with:
      directory: iac/flux/lscsde-configuration
    secrets: inherit
  
  update-repo-branch:
    uses: lsc-sde/lsc-sde/.github/workflows/update-yaml.yaml@main
    needs:
    - package
    with:
      repository: lsc-sde/iac-flux-lscsde
      path: "clusters/prod/lscsde/repository.yaml,clusters/dev/lscsde/repository.yaml"
      yamlPath: .spec.ref.branch
      newValue: "release/${{ needs.package.outputs.semver }}"
    secrets: inherit
  